09:49:04 [main] ERROR com.revature.Driver - Login exception was thrown: com.revature.exceptions.LoginException
